version: "0.1"
services:
  - name: sanctuary-runtime
    image: aaontario/ollama-gpu-runtime:latest
    ports:
      - 11434
      - 3000
      - 8888
    gpu: true
    volumes:
      - /workspace  # NOT /workspace/models
